version: '3'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672

  accumulator2.0.0:
    build:
      context: ./
      dockerfile: Accumulator/Accumulator.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=2.0.0
      - EOF_TO_RECEIVE=1
      - NEXT_POOL_WORKERS=1
      - FORWARD_TO=Gateway
      - DISTRIBUTE_BY=title
      - WORKER_FIELD=year
      - WORKER_VALUE=10
      - ACCUMULATE_BY=authors

  accumulator2.0.1:
    build:
      context: ./
      dockerfile: Accumulator/Accumulator.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=2.0.1
      - EOF_TO_RECEIVE=1
      - NEXT_POOL_WORKERS=1
      - FORWARD_TO=Gateway
      - DISTRIBUTE_BY=title
      - WORKER_FIELD=year
      - WORKER_VALUE=10
      - ACCUMULATE_BY=authors

  accumulator2.0.2:
    build:
      context: ./
      dockerfile: Accumulator/Accumulator.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=2.0.2
      - EOF_TO_RECEIVE=1
      - NEXT_POOL_WORKERS=1
      - FORWARD_TO=Gateway
      - DISTRIBUTE_BY=title
      - WORKER_FIELD=year
      - WORKER_VALUE=10
      - ACCUMULATE_BY=authors

  accumulator2.0.3:
    build:
      context: ./
      dockerfile: Accumulator/Accumulator.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=2.0.3
      - EOF_TO_RECEIVE=1
      - NEXT_POOL_WORKERS=1
      - FORWARD_TO=Gateway
      - DISTRIBUTE_BY=title
      - WORKER_FIELD=year
      - WORKER_VALUE=10
      - ACCUMULATE_BY=authors

  gateway:
    build:
      context: ./
      dockerfile: Gateway/Gateway.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=12345
      - BOOK_QUERIES=2
      - REVIEW_QUERIES=
      - FORWARD_TO=2.0
      - NEXT_POOL_WORKERS=4
      - EOF_TO_RECEIVE=4

  client:
    build:
      context: ./
      dockerfile: Client/Client.dockerfile
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - BATCH_SIZE=25
      - QUERY_RESULTS_PATH=/data/query_results
      - QUERIES=2
      - SERVER_PORT=12345
    volumes:
      - dataVolume:/data

volumes:
  dataVolume:
    driver: local
    driver_opts:
      type: none
      device: ./data
      o: bind