version: '3'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672

  filter1.0.0:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1.0.0
      - NEXT_POOL_WORKERS=2
      - FORWARD_TO=1.1
      - WORKER_FIELD=categories
      - WORKER_VALUE=Biography & Autobiography

  filter1.0.1:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1.0.1
      - NEXT_POOL_WORKERS=2
      - FORWARD_TO=1.1
      - WORKER_FIELD=categories
      - WORKER_VALUE=Biography & Autobiography

  filter1.1.0:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1.1.0
      - NEXT_POOL_WORKERS=1
      - FORWARD_TO=1.2
      - WORKER_FIELD=year
      - WORKER_VALUE=2000,2010

  filter1.1.1:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1.1.1
      - NEXT_POOL_WORKERS=1
      - FORWARD_TO=1.2
      - WORKER_FIELD=year
      - WORKER_VALUE=2000,2010

  filter1.2.0:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1.2.0
      - NEXT_POOL_WORKERS=1
      - FORWARD_TO=Gateway
      - WORKER_FIELD=title
      - WORKER_VALUE=Dr

  accumulator2.0.0:
    build:
      context: ./
      dockerfile: Accumulator/Accumulator.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=2.0.0
      - NEXT_POOL_WORKERS=1
      - FORWARD_TO=Gateway
      - WORKER_FIELD=year
      - WORKER_VALUE=10
      - ACCUMULATE_BY=authors

  filter3.0.0:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=3.0.0
      - NEXT_POOL_WORKERS=1,2
      - FORWARD_TO=Gateway,4.0
      - WORKER_FIELD=year
      - WORKER_VALUE=1990,1999

  filter4.0.0:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=4.0.0
      - NEXT_POOL_WORKERS=1
      - FORWARD_TO=Gateway
      - WORKER_FIELD=categories
      - WORKER_VALUE=Biography & Autobiography

  filter4.0.1:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=4.0.1
      - NEXT_POOL_WORKERS=1
      - FORWARD_TO=Gateway
      - WORKER_FIELD=categories
      - WORKER_VALUE=Biography & Autobiography

  gateway:
    build:
      context: ./
      dockerfile: Gateway/Gateway.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=12345
      - BOOK_QUERIES=1,2
      - REVIEW_QUERIES=1
      - FORWARD_TO=1.0,2.0
      - NEXT_POOL_WORKERS=2,1
      - TOTAL_LAST_WORKERS=5

  client:
    build:
      context: ./
      dockerfile: Client/Client.dockerfile
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1