version: '3'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672

  worker1.0.1:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1.0.1
      - NEXT_POOL_WORKERS=1
      - WORKER_TYPE=Filter
      - WORKER_VALUE=Computers

  worker1.1.1:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1.1.1
      - NEXT_POOL_WORKERS=1
      - WORKER_TYPE=Filter
      - WORKER_VALUE=2000,2023

  worker1.2.1:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1.2.1
      - NEXT_POOL_WORKERS=0
      - WORKER_TYPE=Filter
      - WORKER_VALUE=distributed

  gateway:
    build:
      context: ./
      dockerfile: Gateway/Gateway.dockerfile
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1