version: '3'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672

  filter1.0.0:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1.0.0
      - NEXT_POOL_WORKERS=1
      - WORKER_FIELD=categories
      - WORKER_VALUE=Biography & Autobiography

  filter1.1.0:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1.1.0
      - NEXT_POOL_WORKERS=1
      - WORKER_FIELD=year
      - WORKER_VALUE=2000,2010

  filter1.2.0:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1.2.0
      - NEXT_POOL_WORKERS=0
      - WORKER_FIELD=title
      - WORKER_VALUE=Dr

  accumulator2.0.0:
    build:
      context: ./
      dockerfile: Accumulator/Accumulator.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=2.0.0
      - NEXT_POOL_WORKERS=0
      - WORKER_FIELD=year
      - WORKER_VALUE=10
      - ACCUMULATE_BY=authors

  gateway:
    build:
      context: ./
      dockerfile: Gateway/Gateway.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=12345
      - BOOK_QUERIES=1
      - REVIEW_QUERIES=
      - TOTAL_LAST_WORKERS=2

  client:
    build:
      context: ./
      dockerfile: Client/Client.dockerfile
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - dataVolume:/data

volumes:
  dataVolume:
    driver: local
    driver_opts:
      type: none
      device: ./data
      o: bind