version: '3'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672

  filter1.0.0:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1.0.0
      - EOF_TO_RECEIVE=1
      - NEXT_POOL_WORKERS=3
      - FORWARD_TO=1.1
      - WORKER_FIELD=categories
      - WORKER_VALUE=Computers

  filter1.0.1:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1.0.1
      - EOF_TO_RECEIVE=1
      - NEXT_POOL_WORKERS=3
      - FORWARD_TO=1.1
      - WORKER_FIELD=categories
      - WORKER_VALUE=Computers

  filter1.0.2:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1.0.2
      - EOF_TO_RECEIVE=1
      - NEXT_POOL_WORKERS=3
      - FORWARD_TO=1.1
      - WORKER_FIELD=categories
      - WORKER_VALUE=Computers

  filter1.0.3:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1.0.3
      - EOF_TO_RECEIVE=1
      - NEXT_POOL_WORKERS=3
      - FORWARD_TO=1.1
      - WORKER_FIELD=categories
      - WORKER_VALUE=Computers

  filter1.1.0:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1.1.0
      - EOF_TO_RECEIVE=4
      - NEXT_POOL_WORKERS=4
      - FORWARD_TO=1.2
      - WORKER_FIELD=year
      - WORKER_VALUE=2000,2023

  filter1.1.1:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1.1.1
      - EOF_TO_RECEIVE=4
      - NEXT_POOL_WORKERS=4
      - FORWARD_TO=1.2
      - WORKER_FIELD=year
      - WORKER_VALUE=2000,2023

  filter1.1.2:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1.1.2
      - EOF_TO_RECEIVE=4
      - NEXT_POOL_WORKERS=4
      - FORWARD_TO=1.2
      - WORKER_FIELD=year
      - WORKER_VALUE=2000,2023

  filter1.2.0:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1.2.0
      - EOF_TO_RECEIVE=3
      - NEXT_POOL_WORKERS=1
      - FORWARD_TO=Gateway
      - WORKER_FIELD=title
      - WORKER_VALUE=distributed

  filter1.2.1:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1.2.1
      - EOF_TO_RECEIVE=3
      - NEXT_POOL_WORKERS=1
      - FORWARD_TO=Gateway
      - WORKER_FIELD=title
      - WORKER_VALUE=distributed

  filter1.2.2:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1.2.2
      - EOF_TO_RECEIVE=3
      - NEXT_POOL_WORKERS=1
      - FORWARD_TO=Gateway
      - WORKER_FIELD=title
      - WORKER_VALUE=distributed

  filter1.2.3:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1.2.3
      - EOF_TO_RECEIVE=3
      - NEXT_POOL_WORKERS=1
      - FORWARD_TO=Gateway
      - WORKER_FIELD=title
      - WORKER_VALUE=distributed

  gateway:
    build:
      context: ./
      dockerfile: Gateway/Gateway.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=12345
      - BOOK_QUERIES=1
      - REVIEW_QUERIES=1
      - FORWARD_TO=1.0
      - NEXT_POOL_WORKERS=4
      - EOF_TO_RECEIVE=4

  client:
    build:
      context: ./
      dockerfile: Client/Client.dockerfile
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - BATCH_SIZE=25
      - QUERY_RESULTS_PATH=/data/query_results
      - QUERIES=1
      - SERVER_PORT=12345
    volumes:
      - dataVolume:/data

volumes:
  dataVolume:
    driver: local
    driver_opts:
      type: none
      device: ./data
      o: bind