version: '3'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672

  category_filter1:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1.1.1
      - NEXT_POOL_WORKERS=1
      - FILTER_TYPE=categories
      - FILTER_VALUE=fiction

  category_filter2:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=1.2.1
      - NEXT_POOL_WORKERS=1
      - FILTER_TYPE=year
      - FILTER_VALUE=1990,1999

  gateway:
    build:
      context: ./
      dockerfile: Gateway/Gateway.dockerfile
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1