version: '3'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672

  accumulator2.0.0:
    build:
      context: ./
      dockerfile: Accumulator/Accumulator.dockerfile
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=2.0.0
      - NEXT_POOL_WORKERS=0
      - WORKER_FIELD=year
      - WORKER_VALUE=10
      - ACCUMULATE_BY=authors

  gateway:
    build:
      context: ./
      dockerfile: Gateway/Gateway.dockerfile
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1