version: '3'
services:
  gateway:
    build:
      context: ./
      dockerfile: Gateway/Gateway.dockerfile
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net

  client:
    build:
      context: ./
      dockerfile: Client/Client.dockerfile
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24