version: '3'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672

  filter3.0.0:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=3.0.0
      - EOF_TO_RECEIVE=1
      - NEXT_POOL_WORKERS=4
      - FORWARD_TO=3.1
      - DISTRIBUTE_BY=title
      - WORKER_FIELD=year
      - WORKER_VALUE=1990,1999

  filter3.0.1:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=3.0.1
      - EOF_TO_RECEIVE=1
      - NEXT_POOL_WORKERS=4
      - FORWARD_TO=3.1
      - DISTRIBUTE_BY=title
      - WORKER_FIELD=year
      - WORKER_VALUE=1990,1999

  filter3.0.2:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=3.0.2
      - EOF_TO_RECEIVE=1
      - NEXT_POOL_WORKERS=4
      - FORWARD_TO=3.1
      - DISTRIBUTE_BY=title
      - WORKER_FIELD=year
      - WORKER_VALUE=1990,1999

  filter3.0.3:
    build:
      context: ./
      dockerfile: Filter/Filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=3.0.3
      - EOF_TO_RECEIVE=1
      - NEXT_POOL_WORKERS=4
      - FORWARD_TO=3.1
      - DISTRIBUTE_BY=title
      - WORKER_FIELD=year
      - WORKER_VALUE=1990,1999

  accumulator3.1.0:
    build:
      context: ./
      dockerfile: Accumulator/Accumulator.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=3.1.0
      - EOF_TO_RECEIVE=4
      - NEXT_POOL_WORKERS=1
      - FORWARD_TO=Gateway
      - DISTRIBUTE_BY=title
      - WORKER_FIELD=review_count
      - WORKER_VALUE=500
      - ACCUMULATE_BY=title

  accumulator3.1.1:
    build:
      context: ./
      dockerfile: Accumulator/Accumulator.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=3.1.1
      - EOF_TO_RECEIVE=4
      - NEXT_POOL_WORKERS=1
      - FORWARD_TO=Gateway
      - DISTRIBUTE_BY=title
      - WORKER_FIELD=review_count
      - WORKER_VALUE=500
      - ACCUMULATE_BY=title

  accumulator3.1.2:
    build:
      context: ./
      dockerfile: Accumulator/Accumulator.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=3.1.2
      - EOF_TO_RECEIVE=4
      - NEXT_POOL_WORKERS=1
      - FORWARD_TO=Gateway
      - DISTRIBUTE_BY=title
      - WORKER_FIELD=review_count
      - WORKER_VALUE=500
      - ACCUMULATE_BY=title

  accumulator3.1.3:
    build:
      context: ./
      dockerfile: Accumulator/Accumulator.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - WORKER_ID=3.1.3
      - EOF_TO_RECEIVE=4
      - NEXT_POOL_WORKERS=1
      - FORWARD_TO=Gateway
      - DISTRIBUTE_BY=title
      - WORKER_FIELD=review_count
      - WORKER_VALUE=500
      - ACCUMULATE_BY=title

  gateway:
    build:
      context: ./
      dockerfile: Gateway/Gateway.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=12345
      - BOOK_QUERIES=3
      - REVIEW_QUERIES=3
      - FORWARD_TO=3.0
      - NEXT_POOL_WORKERS=4
      - EOF_TO_RECEIVE=4

  client:
    build:
      context: ./
      dockerfile: Client/Client.dockerfile
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1
      - BATCH_SIZE=25
      - QUERY_RESULTS_PATH=/data/query_results
      - QUERIES=3
      - SERVER_PORT=12345
    volumes:
      - dataVolume:/data

volumes:
  dataVolume:
    driver: local
    driver_opts:
      type: none
      device: ./data
      o: bind